# Site settings
title: Akamyoyel's Blog
description: It's just a daily routine.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Akamyoyel
user_description:
user_title: 
email: nomajel@naver.com
twitter_username: Aka_myoyel
github_username: Akamyoyel
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
